### ISSUE TITLE
Etherport Not Running 

### ISSUE THREAD

**Issue by alfredoborrero** [mwittig/etherport-client#1] opened 2016-06-26 00:19 UTC
Hi, I am traying to connect a ESP8266 D1 Mini and i am having timeout issues.
This is a chineese version:
http://www.aliexpress.com/item/Smart-Electronics-D1-mini-Mini-NodeMcu-4M-bytes-Lua-WIFI-Internet-of-Things-development-board-based/32628017688.html

I installed latest version of the Arduino Library (Firmata Version 2.5.3) https://github.com/firmata/arduino and i was able add the parameters to wifiConfig.h and finally I uploaded the firmware to my ESP8266 Board (StandardFirmataWiFi.ino).

I also uncommented the line #85, so I enabled the serial debugging. And I was able to see when the board connects to my house SSID and I get a decent signal strength (-66 dBm), I can actually specify the local static IP Address or let the routher assign a Dynamic IP address from the DHCP. So its actually connecting to my WiFi Network.

The problem that I have right now is that I have timeout error when I run the Javascript file in nodeJS. And I tried with 4 different boards already. Is there anything i can do to troubleshoot this?

```
var five = require("johnny-five");
var EtherPortClient = require("etherport-client").EtherPortClient;
var board = new five.Board({
     port: new EtherPortClient({
          host: "192.168.1.64",
          port: 3030
     }),
     timeout: 1e5,
     repl: false
});

board.on("ready", function() {
     console.log("READY!");
     var led = new five.Led(2);
     led.blink(500);
});
```

All I am trying to do is run the board as a Client and the server is a local host in my PC (192.168.1.64), I installed the NodeJS as well. Actually I run multiple Arduino's MEGA and Particle and I haven got any issues, for some reason I am having problems with the D1 Mini. I already read all the comments in this forum and I think I was able to troubleshoot everything but still is not working :-(

Any help would be appreciated.

Regards,

Alfredo Borrero

**Comment by mwittig** [comment] 2016-06-26 09:37
> and the server is a local host in my PC (192.168.1.64)

I am confused. You should provide the IP address assigned to the D1 Mini. 

> I can actually specify the local static IP Address or let the routher assign a Dynamic IP address from the DHCP

Use DHCP and pick the IP address which has been assigned from by the router's DHCP server. The router management software should provide some kind of network view which shows all connected devices and IP addresses.

**Comment by alfredoborrero** [comment] 2016-06-26 15:38
Thanks for the clarification, but i still have issues :-(The assigned IP Adresss for my D1 Mini board is 192.168.1.84 (as you can see in the attached picture) and that is the one that i declared in my JS file, howevever is not connecting when i try to run it in NodeJS
Regards,
Alfredo Borrero

Date: Sun, 26 Jun 2016 02:37:44 -0700

**Comment by mwittig** [comment] 2016-06-27 10:36
Regarding, STEP 4 in wifiConfig.h, what is your current setup? If you use DHCP, the three macros STATIC_IP_ADDRESS, SUBNET_MASK, GATEWAY_IP_ADDRESS shall not be defined. For a static IP configuration all three must be setup.

Btw, I have the same board and it works for me with an earlier version of firmata (esp branch). I will pick the latest version and will try to reproduce the problem. Generally, I don't think it is a problem with J5 or EtherportClient.

**Comment by ronaldogaraujo** [comment] 2016-08-03 10:22
Hi, I am trying to connect a Ethernet Shield W5100 (arduino uno) and I am having timeout issues.

I installed latest version of the Arduino Library (Firmata Version 2.5.3) and I was able add the parameters to ethernetConfig.h: 

remote_ip    = my node server         -> 192.168.13.249
local_ip        = my ethernet shield's -> 192.168.13.250 
remote_port -> 3030

I ping both IP's.

My nodeJS file (j5.js) is:
```
var five = require("johnny-five");
var EtherPortClient = require("etherport-client").EtherPortClient;
var board = new five.Board({
     port: new EtherPortClient({
          host: "192.168.13.250",
          port: 3030
     }),
     timeout: 1e5,
     repl: false
});

board.on("ready", function() {
     console.log("OK !!!!");
     var led = new five.Led(9);
     led.blink(300);
});
```
When I execute node j5.js, the messages are:
```
1470218729945 SerialPort Connecting to host:port: 192.168.13.250:3030
1470218729955 Connected Connecting to host:port: 192.168.13.250:3030
1470218739958 Device or Firmware Error A timeout occurred while connecting to the Board.
```
I'm doing something wrong , but do not know what it is.

Can you help me ?

Thanks and sorry about my English.

Ronaldo Araujo

**Comment by mwittig** [comment] 2017-03-04 10:09
@ronaldogaraujo Sorry, I overlooked you post. Did you managed to get it to work?

**Comment by mwittig** [comment] 2017-05-10 10:33
I am closing this now as there has been no follow-up since months.

**Closed as completed by mwittig** 2017-05-10 10:33 UTC
